openapi: 3.0.0
info:
  title: 게시물 댓글 관리 API
  description: 게시물의 댓글을 조회, 등록, 수정, 삭제하기 위한 API.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: 개발 서버 (로컬 데이터 사용)

paths:
  /articles/{articleId}/comments/:
    get:
      summary: 게시물의 댓글 목록 조회
      description: 특정 게시물의 모든 댓글을 조회합니다.
      parameters:
        - name: articleId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 댓글 목록
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'

    post:
      summary: 게시물에 댓글 등록
      description: 특정 게시물에 새로운 댓글을 등록합니다.
      parameters:
        - name: articleId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentCreate'
      responses:
        '200':
          description: 댓글 등록됨

  /articles/{articleId}/comments/{commentId}:
    put:
      summary: 댓글 수정
      description: 특정 게시물의 특정 댓글을 수정합니다.
      parameters:
        - name: articleId
          in: path
          required: true
          schema:
            type: integer
        - name: commentId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentUpdate'
      responses:
        '200':
          description: 댓글 수정됨

    delete:
      summary: 댓글 삭제
      description: 특정 게시물의 특정 댓글을 삭제합니다.
      parameters:
        - name: articleId
          in: path
          required: true
          schema:
            type: integer
        - name: commentId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 댓글 삭제됨

components:
  schemas:
    Comment:
      type: object
      properties:
        id:
          type: integer
          example: 1
        author:
          type: string
          example: "홍길동"
        content:
          type: string
          example: "댓글 내용입니다."
        createdAt:
          type: string
          format: date-time
          example: "2023-01-01T12:00:00"
        updatedAt:
          type: string
          format: date-time
          example: "2023-01-02T15:30:00"
    CommentCreate:
      type: object
      properties:
        author:
          type: string
          example: "홍길동"
        content:
          type: string
          example: "새 댓글 내용입니다."
    CommentUpdate:
      type: object
      properties:
        content:
          type: string
          example: "수정된 댓글 내용입니다."